#
#   This version is for the caddy reverse proxy
#
version: '3.7'

volumes:
  db_backups:
    name: geoserver_postgis_backups

  geoserver_data:
    name: geoserver_data
    # /geoserver/gwc is the GEOWEBCACHE_CACHE_DIR and contains geowebcache.xml

  geoserver_pgadmin:
    name: geoserver_pgadmin

networks:
  # This is a network we share with our reverse proxy
  proxy:
    name: proxy
    # Won't be created or destroyed with docker-compose up|down
    external: true

  # This network is only used for database access
  postgis_net:
    name: postgis_net

services:
  db-backups:
    container_name: geoserver-db-backup
    image: kartoza/pg-backup:11.0
    environment:
      PGUSER: postgres
      PGPASSWORD: ${DB_ADMIN_PASSWORD}
      PGHOST: bellman
    networks:
      - postgis_net
    volumes:
      - db_backups:/backups
    restart: unless-stopped

THIS IS NOT WORKING YET VIA CADDY, it's not visible on the net.
KEY IS GENERATED

  geoserver:
    container_name: geoserver
    build:
      context: .
      dockerfile: Dockerfile.geoserver
    image: wildsong/geoserver:latest
    environment:
      TZ: "America/Los_Angeles"
      ENABLE_JSONP: "true"
      GEOSERVER_DATA_DIR: /geoserver
      GEOWEBCACHE_DATA_DIR: /geoserver/gwc
      GEOSERVER_CSRF_WHITELIST: ${GEOSERVER_CSRF_WHITELIST}
      GEOSERVER_CSRF_DISABLED: ${GEOSERVER_CSRF_DISABLED}
    networks:
      - proxy
      - postgis_net
    volumes:
      - geoserver_data:/geoserver
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      # I think that when this container starts up,
      # the 'caddy' container will see it and generate a new Caddyfile
      # but what happens here?? Does it generate a Caddyfile here too?
      caddy: geoserver.${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls.protocols: "tls1.3"
      caddy.tls.dns: "cloudflare ${API_TOKEN}"
   
  pgadmin:
    container_name: geoserver-pgadmin
    # dpage/pgadmin4 is the official release
    image: dpage/pgadmin4:5.5
    networks:
      - proxy
      - postgis_net
    volumes:
      # Session data, user files, config files, config database go here.
      - geoserver_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      # I think that when this container starts up,
      # the 'caddy' container will see it and generate a new Caddyfile
      # but what happens here?? Does it generate a Caddyfile here too?
      caddy: pgadmin.${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls.protocols: "tls1.3"
      caddy.tls.dns: "cloudflare ${API_TOKEN}"
   

